/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.introduction;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
@SpringBootTest
public class AppIT {

    @Test
    public void contextLoads() {
    }

}
